/**
 * LENSTRACK LENS DATABASE
 * Complete product catalog with full tagging structure
 */

export const lensDatabase = [
  // ==================== SINGLE VISION LENSES ====================
  
  {
    name: 'HardX',
    vision_type: 'SV',
    index: 1.50,
    blue_protection_level: 0,
    uv_protection_level: 1,
    ar_level: 1,
    driving_support_level: 0,
    photochromic: false,
    min_power_supported: -8,
    max_power_supported: 8,
    frame_compatibility: ['full_rim_plastic', 'full_rim_metal'],
    price_mrp: 300,
    numericPrice: 300,
    price_segment: 'budget',
    features: ['Scratch Armor', 'Durable coating'],
    dailyCost: '₹1'
  },
  
  {
    name: 'Pureview',
    vision_type: 'SV',
    index: 1.56,
    blue_protection_level: 0,
    uv_protection_level: 2,
    ar_level: 3,
    driving_support_level: 1,
    photochromic: false,
    min_power_supported: -8,
    max_power_supported: 8,
    frame_compatibility: ['full_rim_plastic', 'full_rim_metal'],
    price_mrp: 500,
    numericPrice: 500,
    price_segment: 'budget',
    features: ['AR Multilayer', 'Clarity'],
    dailyCost: '₹1.5'
  },
  
  {
    name: 'BlueXpert',
    vision_type: 'SV',
    index: 1.60,
    blue_protection_level: 3,
    uv_protection_level: 2,
    ar_level: 3,
    driving_support_level: 1,
    photochromic: false,
    min_power_supported: -8,
    max_power_supported: 8,
    frame_compatibility: ['full_rim_plastic', 'full_rim_metal', 'half_rim', 'semi_rimless'],
    price_mrp: 800,
    numericPrice: 800,
    price_segment: 'mid',
    features: ['Blue Light Block', 'AR Multilayer'],
    dailyCost: '₹2'
  },
  
  {
    name: 'DuraShield Nature',
    vision_type: 'SV',
    index: 1.60,
    blue_protection_level: 2,
    uv_protection_level: 3,
    ar_level: 4,
    driving_support_level: 2,
    photochromic: false,
    min_power_supported: -8,
    max_power_supported: 8,
    frame_compatibility: ['full_rim_plastic', 'full_rim_metal', 'half_rim', 'semi_rimless'],
    price_mrp: 2000,
    numericPrice: 2000,
    price_segment: 'mid',
    features: ['Dual Side AR + Fluoropolymer', 'Natural colour perception'],
    dailyCost: '₹5'
  },
  
  {
    name: 'DriveXpert',
    vision_type: 'SV',
    index: 1.60,
    blue_protection_level: 2,
    uv_protection_level: 3,
    ar_level: 4,
    driving_support_level: 5,
    photochromic: false,
    min_power_supported: -8,
    max_power_supported: 8,
    frame_compatibility: ['full_rim_plastic', 'full_rim_metal', 'half_rim', 'semi_rimless'],
    price_mrp: 2500,
    numericPrice: 2500,
    price_segment: 'mid',
    features: ['Driving protection', 'Hydrophobic & Oleophobic'],
    dailyCost: '₹6'
  },
  
  {
    name: 'DIGI360 Advanced',
    vision_type: 'SV',
    index: 1.67,
    blue_protection_level: 5,
    uv_protection_level: 4,
    ar_level: 5,
    driving_support_level: 3,
    photochromic: false,
    min_power_supported: -10,
    max_power_supported: 10,
    frame_compatibility: ['full_rim_plastic', 'full_rim_metal', 'half_rim', 'semi_rimless'],
    price_mrp: 3000,
    numericPrice: 3000,
    price_segment: 'premium',
    features: ['360° Digital Protection', 'Blue Light Block', 'UV + Sun protection'],
    dailyCost: '₹8'
  },
  
  {
    name: 'DIGI360 Advanced (High Index)',
    vision_type: 'SV',
    index: 1.74,
    blue_protection_level: 5,
    uv_protection_level: 4,
    ar_level: 5,
    driving_support_level: 3,
    photochromic: false,
    min_power_supported: -15,
    max_power_supported: 15,
    frame_compatibility: ['full_rim_plastic', 'full_rim_metal', 'half_rim', 'semi_rimless'],
    price_mrp: 4500,
    numericPrice: 4500,
    price_segment: 'premium',
    features: ['360° Digital Protection', 'Blue Light Block', 'UV + Sun protection', 'Ultra-thin'],
    dailyCost: '₹12'
  },
  
  // ==================== PROGRESSIVE LENSES ====================
  
  {
    name: 'HardX (Progressive)',
    vision_type: 'progressive',
    index: 1.50,
    blue_protection_level: 0,
    uv_protection_level: 1,
    ar_level: 1,
    driving_support_level: 0,
    photochromic: false,
    min_power_supported: -6,
    max_power_supported: 6,
    frame_compatibility: ['full_rim_plastic', 'full_rim_metal'],
    price_mrp: 1500,
    numericPrice: 1500,
    price_segment: 'budget',
    features: ['Everyday Scratch Armor'],
    dailyCost: '₹4'
  },
  
  {
    name: 'Pureview (Progressive)',
    vision_type: 'progressive',
    index: 1.56,
    blue_protection_level: 0,
    uv_protection_level: 2,
    ar_level: 3,
    driving_support_level: 1,
    photochromic: false,
    min_power_supported: -6,
    max_power_supported: 6,
    frame_compatibility: ['full_rim_plastic', 'full_rim_metal'],
    price_mrp: 2000,
    numericPrice: 2000,
    price_segment: 'mid',
    features: ['AR Multilayer'],
    dailyCost: '₹5'
  },
  
  {
    name: 'BlueXpert (Progressive)',
    vision_type: 'progressive',
    index: 1.60,
    blue_protection_level: 3,
    uv_protection_level: 2,
    ar_level: 3,
    driving_support_level: 1,
    photochromic: false,
    min_power_supported: -6,
    max_power_supported: 6,
    frame_compatibility: ['full_rim_plastic', 'full_rim_metal', 'half_rim', 'semi_rimless'],
    price_mrp: 3500,
    numericPrice: 3500,
    price_segment: 'mid',
    features: ['Absorbers + AR Multilayer', 'Blue Light Block'],
    dailyCost: '₹10'
  },
  
  {
    name: 'VisionX Neo',
    vision_type: 'progressive',
    index: 1.60,
    blue_protection_level: 2,
    uv_protection_level: 3,
    ar_level: 4,
    driving_support_level: 3,
    photochromic: false,
    min_power_supported: -6,
    max_power_supported: 6,
    frame_compatibility: ['full_rim_plastic', 'full_rim_metal', 'half_rim', 'semi_rimless'],
    price_mrp: 6000,
    numericPrice: 6000,
    price_segment: 'premium',
    features: ['Dual side AR + Fluoropolymer', 'Wide field of vision'],
    dailyCost: '₹16'
  },
  
  {
    name: 'VisionX Elite',
    vision_type: 'progressive',
    index: 1.67,
    blue_protection_level: 3,
    uv_protection_level: 4,
    ar_level: 5,
    driving_support_level: 4,
    photochromic: false,
    min_power_supported: -8,
    max_power_supported: 8,
    frame_compatibility: ['full_rim_plastic', 'full_rim_metal', 'half_rim', 'semi_rimless'],
    price_mrp: 8000,
    numericPrice: 8000,
    price_segment: 'premium',
    features: ['Pupillary Light Reflex compatibility', 'Smooth power transition'],
    dailyCost: '₹21'
  },
  
  {
    name: 'VisionX Ultra',
    vision_type: 'progressive',
    index: 1.74,
    blue_protection_level: 4,
    uv_protection_level: 5,
    ar_level: 5,
    driving_support_level: 5,
    photochromic: false,
    min_power_supported: -10,
    max_power_supported: 10,
    frame_compatibility: ['full_rim_plastic', 'full_rim_metal', 'half_rim', 'semi_rimless'],
    price_mrp: 12000,
    numericPrice: 12000,
    price_segment: 'ultra',
    features: ['ION Bombardment technology', 'Premium, wide field of vision'],
    dailyCost: '₹32'
  },
  
  // ==================== BIFOCAL LENSES ====================
  
  {
    name: 'Pureview (Bifocal)',
    vision_type: 'bifocal',
    index: 1.56,
    blue_protection_level: 0,
    uv_protection_level: 2,
    ar_level: 3,
    driving_support_level: 1,
    photochromic: false,
    min_power_supported: -6,
    max_power_supported: 6,
    frame_compatibility: ['full_rim_plastic', 'full_rim_metal'],
    price_mrp: 1800,
    numericPrice: 1800,
    price_segment: 'budget',
    features: ['AR Multilayer'],
    dailyCost: '₹5'
  },
  
  {
    name: 'BlueXpert (Bifocal)',
    vision_type: 'bifocal',
    index: 1.60,
    blue_protection_level: 3,
    uv_protection_level: 2,
    ar_level: 3,
    driving_support_level: 1,
    photochromic: false,
    min_power_supported: -6,
    max_power_supported: 6,
    frame_compatibility: ['full_rim_plastic', 'full_rim_metal', 'half_rim', 'semi_rimless'],
    price_mrp: 2000,
    numericPrice: 2000,
    price_segment: 'mid',
    features: ['Blue Light Filter', 'AR Multilayer'],
    dailyCost: '₹6'
  },
  
  {
    name: 'DriveXpert (Bifocal)',
    vision_type: 'bifocal',
    index: 1.60,
    blue_protection_level: 2,
    uv_protection_level: 3,
    ar_level: 4,
    driving_support_level: 5,
    photochromic: false,
    min_power_supported: -6,
    max_power_supported: 6,
    frame_compatibility: ['full_rim_plastic', 'full_rim_metal', 'half_rim', 'semi_rimless'],
    price_mrp: 3500,
    numericPrice: 3500,
    price_segment: 'mid',
    features: ['Driving Protection'],
    dailyCost: '₹10'
  },
  
  {
    name: 'DIGI360 Advanced (Bifocal)',
    vision_type: 'bifocal',
    index: 1.67,
    blue_protection_level: 5,
    uv_protection_level: 4,
    ar_level: 5,
    driving_support_level: 3,
    photochromic: false,
    min_power_supported: -8,
    max_power_supported: 8,
    frame_compatibility: ['full_rim_plastic', 'full_rim_metal', 'half_rim', 'semi_rimless'],
    price_mrp: 4000,
    numericPrice: 4000,
    price_segment: 'premium',
    features: ['Advanced digital filter'],
    dailyCost: '₹12'
  },
  
  // ==================== ZERO POWER LENSES ====================
  
  {
    name: 'BlueXpert (Zero Power)',
    vision_type: 'zero_power',
    index: 1.50,
    blue_protection_level: 3,
    uv_protection_level: 2,
    ar_level: 3,
    driving_support_level: 1,
    photochromic: false,
    min_power_supported: 0,
    max_power_supported: 0,
    frame_compatibility: ['full_rim_plastic', 'full_rim_metal', 'half_rim', 'semi_rimless', 'rimless', 'drilled'],
    price_mrp: 800,
    numericPrice: 800,
    price_segment: 'mid',
    features: ['Blue Light Block', 'AR Multilayer'],
    dailyCost: '₹2'
  },
  
  {
    name: 'DIGI360 Advanced (Zero Power)',
    vision_type: 'zero_power',
    index: 1.60,
    blue_protection_level: 5,
    uv_protection_level: 4,
    ar_level: 5,
    driving_support_level: 3,
    photochromic: false,
    min_power_supported: 0,
    max_power_supported: 0,
    frame_compatibility: ['full_rim_plastic', 'full_rim_metal', 'half_rim', 'semi_rimless', 'rimless', 'drilled'],
    price_mrp: 3000,
    numericPrice: 3000,
    price_segment: 'premium',
    features: ['360° Digital Protection', 'Blue Light Block', 'UV + Sun protection'],
    dailyCost: '₹8'
  },
  
  // ==================== PHOTOCHROMIC LENSES ====================
  
  {
    name: 'BlueXpert Photochromic',
    vision_type: 'SV',
    index: 1.60,
    blue_protection_level: 3,
    uv_protection_level: 5,
    ar_level: 3,
    driving_support_level: 2,
    photochromic: true,
    min_power_supported: -8,
    max_power_supported: 8,
    frame_compatibility: ['full_rim_plastic', 'full_rim_metal', 'half_rim', 'semi_rimless'],
    price_mrp: 3500,
    numericPrice: 3500,
    price_segment: 'premium',
    features: ['Blue Light Block', 'Auto-tint in sunlight', 'AR Multilayer'],
    dailyCost: '₹10'
  },
  
  {
    name: 'DIGI360 Photochromic',
    vision_type: 'SV',
    index: 1.67,
    blue_protection_level: 5,
    uv_protection_level: 5,
    ar_level: 5,
    driving_support_level: 4,
    photochromic: true,
    min_power_supported: -10,
    max_power_supported: 10,
    frame_compatibility: ['full_rim_plastic', 'full_rim_metal', 'half_rim', 'semi_rimless'],
    price_mrp: 5000,
    numericPrice: 5000,
    price_segment: 'premium',
    features: ['360° Digital Protection', 'Auto-tint in sunlight', 'UV + Sun protection'],
    dailyCost: '₹14'
  },
  
  // ==================== RIMLESS COMPATIBLE HIGH INDEX ====================
  
  {
    name: 'Pureview Rimless',
    vision_type: 'SV',
    index: 1.60,
    blue_protection_level: 0,
    uv_protection_level: 2,
    ar_level: 3,
    driving_support_level: 1,
    photochromic: false,
    min_power_supported: -6,
    max_power_supported: 6,
    frame_compatibility: ['rimless', 'drilled', 'full_rim_plastic', 'full_rim_metal', 'half_rim', 'semi_rimless'],
    price_mrp: 1200,
    numericPrice: 1200,
    price_segment: 'mid',
    features: ['AR Multilayer', 'Rimless compatible'],
    dailyCost: '₹3'
  },
  
  {
    name: 'DriveXpert Rimless',
    vision_type: 'SV',
    index: 1.67,
    blue_protection_level: 2,
    uv_protection_level: 3,
    ar_level: 4,
    driving_support_level: 5,
    photochromic: false,
    min_power_supported: -6,
    max_power_supported: 6,
    frame_compatibility: ['rimless', 'drilled', 'full_rim_plastic', 'full_rim_metal', 'half_rim', 'semi_rimless'],
    price_mrp: 3500,
    numericPrice: 3500,
    price_segment: 'premium',
    features: ['Driving protection', 'Rimless compatible'],
    dailyCost: '₹10'
  },
  
  {
    name: 'Ultra Thin Rimless',
    vision_type: 'SV',
    index: 1.74,
    blue_protection_level: 3,
    uv_protection_level: 4,
    ar_level: 5,
    driving_support_level: 4,
    photochromic: false,
    min_power_supported: -6,
    max_power_supported: 6,
    frame_compatibility: ['rimless', 'drilled', 'full_rim_plastic', 'full_rim_metal', 'half_rim', 'semi_rimless'],
    price_mrp: 6000,
    numericPrice: 6000,
    price_segment: 'ultra',
    features: ['Ultra-thin', 'Rimless compatible', 'Premium AR'],
    dailyCost: '₹16'
  }
];

